table_name: birth_names
main_dttm_col: ds
description: null
default_endpoint: null
offset: 0
cache_timeout: null
schema: null
sql: null
params: '{"remote_id": 3, "database_name": "examples", "import_time": 1604342885}'
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
uuid: 74880c15-ddf0-4081-bb40-229a15fa4c6f
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  extra: null
  warning_text: null
- metric_name: sum__num
  verbose_name: null
  metric_type: null
  expression: SUM(num)
  description: null
  d3format: null
  extra: null
  warning_text: null
columns:
- column_name: num_california
  verbose_name: null
  is_dttm: false
  is_active: true
  type: null
  groupby: true
  filterable: true
  expression: CASE WHEN state = 'CA' THEN num ELSE 0 END
  description: null
  python_date_format: null
- column_name: state
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR(10)
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
- column_name: gender
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR(16)
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
- column_name: name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR(255)
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
- column_name: ds
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATETIME
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
- column_name: sum_boys
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
- column_name: sum_girls
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
- column_name: num
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
version: 1.0.0
database_uuid: a2dc77af-e654-49bb-b321-40f6b559a1ee
